package deepbluehaven.pojo.enums;

public enum RoleTag {
    VIEW_BOOKING,
    CREATE_BOOKING,
    CANCEL_BOOKING,
    CHECK_IN,
    CHECK_OUT,
    ASSIGN_ROOM,

    CREATE_SERVICE_ORDER,
    PROCESS_SERVICE_ORDER,

    CREATE_INVOICE,
    PROCESS_PAYMENT,
    APPLY_DISCOUNT,

    VIEW_TASK,
    UPDATE_TASK_STATUS,

    MANAGE_WORKER,
    MANAGE_ROOM,
    MANAGE_SERVICE,
    MANAGE_INVENTORY,
    MANAGE_DISCOUNT,
    MANAGE_PRICING,
    MANAGE_MEMBERSHIP,
    VIEW_REPORT,
    MANAGE_COMMENT
}